---
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: csi-cosi-adapter
spec:
  volumeLifecycleModes: # added in Kubernetes 1.16, this field is beta
    - Ephemeral
---
apiVersion: v1
kind: Namespace
metadata:
  name: cosi-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-cosi-adapter
  namespace: cosi-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-cosi
rules:
  - apiGroups:
      - cosi.sigs.k8s.io
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-cosi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-cosi
subjects:
  - kind: ServiceAccount
    name: csi-cosi-adapter
    namespace: cosi-system
---
kind: Pod  # todo convert to DS
apiVersion: v1
metadata:
  name: csi-cosi-adapter
  namespace: cosi-system
spec:
  serviceAccountName: csi-cosi-adapter
  containers:
    - image: quay.io/jcope/csi-cosi-adapter
      name: csi-cosi-adapter
      imagePullPolicy: Never
      args:
        - "--nodeid=$(CSI_COSI_NODE_ID)"
        - "--listen=/csi/csi.sock"
        - "--protocol=unix"
      env:
        - name: CSI_COSI_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: mountpoint-dir
          mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
      securityContext:
        privileged: true
    - name: node-driver-registrar
      image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
      imagePullPolicy: IfNotPresent
      args:
        - "--csi-address=/csi/csi.sock"
        - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi-cosi-adapter/csi.sock"
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm -rf /registration/csi-cosi-adapter-reg.sock /registration/csi-cosi-adapter-reg.sock"]
      volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: registration-dir
          mountPath: /registration
      securityContext:
        privileged: true
  volumes:
    - name: registration-dir
      hostPath:
        path: /var/lib/kubelet/plugins_registry/
        type: Directory
    - name: socket-dir
      hostPath:
        path: /var/lib/kubelet/plugins/csi-cosi-adapter/
        type: DirectoryOrCreate
    - name: mountpoint-dir
      hostPath:
        path: /var/lib/kubelet/pods
        type: Directory